[package]
name = "serde-odbc"
version = "0.1.0"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]

[dependencies]
odbc-sys = "0.5"
serde = "1.0"
serde_derive = "1.0"
typenum = "1.9"
generic-array = "0.9"

[dev-dependencies]
futures = "0.1"
hyper = "0.11"
serde_json = "1.0"
